name: Deploy to AKS with Helm

on:
  push:
    branches:
      - feature/init

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/carstore:${{ github.sha }} .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/carstore:${{ github.sha }}

    - name: Set AKS credentials
      run: az aks get-credentials --resource-group ${{ secrets.AKS_RG }} --name ${{ secrets.AKS_NAME }} --overwrite-existing

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy with Helm
      run: |
        helm upgrade --install carstore ./helm \
          --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/carstore \
          --set image.tag=${{ github.sha }} \
          --namespace default
